services:
  api:
    build: ./backend
    container_name: taskwall-api
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
      - DATABASE_URL=sqlite:///data/taskwall.db
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  web:
    build: ./frontend
    container_name: taskwall-web
    depends_on:
      - api
    ports:
      - "3000:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  taskwall_data:
    driver: local

networks:
  default:
    name: taskwall-network